# Base training configuration
defaults:
  - model: stacked
  - data: mackey_glass
  - _self_

train:
  seed: 42
  batch_size: 32
  max_epochs: 100
  lr: 1e-3
  weight_decay: 1e-4
  gradient_clip: 1.0
  precision: 32  # Use 16 for mixed precision
  num_workers: 4

logging:
  use_wandb: false  # Disabled to avoid import errors
  project_name: delay-no
  entity: null  # Your wandb username or team name
  log_steps: 50

# Hydra configuration to avoid warning about future versions not changing working directory
hydra:
  job:
    chdir: True  # Explicitly set to True to maintain current behavior
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
